# Generated by Django 3.2.9 on 2022-01-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_Image',
            field=models.ImageField(default='NO_Image', upload_to='foodimg'),
        ),
    ]
