# Generated by Django 3.2.9 on 2022-01-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('f_name', models.CharField(max_length=30)),
                ('l_name', models.CharField(max_length=30)),
                ('mobileno', models.BigIntegerField(unique=True)),
                ('role', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('is_superuser', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
